[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["tactool"]

[project]
name = "tactool"
description = "TACtool: A targeting and co-ordination tool for spatial sampling and data traceability applied to scanning electron microscopy and laser ablation ICP-MS"
version = "1.3.1"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
keywords = ["targeting", "co-ordination", "spatial", "traceability", "scanning", "electron", "microscopy", "sem", "laser", "ablation", "icp-ms", "gui"]
requires-python = ">=3.11"
dynamic = ["readme"]
dependencies = [
    "numpy",
    "pyqt5",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
authors = [
    {name="Leo Rudczenko", email="leorud@bgs.ac.uk"},
    {name="John Stevenson", email="jostev@bgs.ac.uk"},
    {name="Connor Newstead", email="connor.newstead@npl.co.uk"},
    {name="Matthew Horstwood", email="msah@bgs.ac.uk"},
]

[project.urls]
repository = "https://github.com/BritishGeologicalSurvey/tactool/"

[project.optional-dependencies]
test = ["pytest", "flake8"]
pyinstaller = ["pyinstaller"]

[project.scripts]
tactool = "tactool.main:main"

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type="text/markdown"}
