name: Create Distributable Files

on:
  release:
    types:
      - released

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            app_file_ext: "exe"
            asset_file_ext: "exe"
          - os: macos
            app_file_ext: "app"
            asset_file_ext: "zip"
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Activate Anaconda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environments/${{ matrix.os }}-environment.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Build with PyInstaller
      shell: bash -l {0}
      run: pyinstaller --name="tactool" --windowed --paths=. --onefile tactool/main.py

    - name: ZIP Application
      if: matrix.os == 'macos'
      run: |
        cd dist
        zip -r tactool.${{ matrix.asset_file_ext }} tactool.${{ matrix.app_file_ext }}

    - name: Get Release Info
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Add Asset to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: dist/tactool.${{ matrix.asset_file_ext }}
        asset_name: ${{ matrix.os }}-tactool.${{ matrix.asset_file_ext }}
        asset_content_type: application
