name: Create Distributable Files

on:
  push:
    paths:
      - '.github/workflows/main.yml'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            app_file_ext: "exe"
            asset_file_ext: "exe"
          - os: macos
            app_file_ext: "app"
            asset_file_ext: "zip"
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Activate Anaconda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.13
        miniconda-version: latest
        auto-activate-base: false

    - name: Build Environment
      shell: bash -l {0}
      run: |
        conda create -n tactool python=3.13
        conda activate tactool
        pip install -e .[pyinstaller]

    - name: Build with PyInstaller
      shell: bash -l {0}
      run: pyinstaller --name="tactool" --windowed --paths=. --onefile tactool/main.py

    - name: ZIP Application
      if: matrix.os == 'macos'
      run: |
        cd dist
        zip -r tactool.${{ matrix.asset_file_ext }} tactool.${{ matrix.app_file_ext }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-tactool.${{ matrix.asset_file_ext }}
        path: dist/tactool.${{ matrix.asset_file_ext }}
