name: Create Distributable Files

on:
  release:
    types:
      - released

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            app_file_ext: "exe"
            asset_file_ext: "exe"
          - os: macos
            app_file_ext: "app"
            asset_file_ext: "zip"
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3

    - name: Activate Anaconda Environment
      uses: conda-incubator/setup-miniconda@11ae174708d1ae769b9457e7d6ed64d606c99af1  # v2
      with:
        miniconda-version: latest
        activate-environment: tactool
        auto-activate-base: false

    - name: Build Environment
      run: |
        conda create -n tactool python=3.13
        conda activate tactool
        pip install -e ".[pyinstaller]"

    - name: Build with PyInstaller
      run: pyinstaller --name="tactool" --windowed --paths=. --onefile tactool/main.py

    - name: ZIP Application
      if: matrix.os == 'macos'
      run: |
        cd dist
        zip -r tactool.${{ matrix.asset_file_ext }} tactool.${{ matrix.app_file_ext }}

    - name: Get Release Info
      id: get_release
      uses: bruceadams/get-release@74c3d60f5a28f358ccf241a00c9021ea16f0569f  # v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Add Asset to Release
      uses: actions/upload-release-asset@48c0418f0e48b7aaf6b7752feec35df6f212beaa  # v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: dist/tactool.${{ matrix.asset_file_ext }}
        asset_name: ${{ matrix.os }}-tactool.${{ matrix.asset_file_ext }}
        asset_content_type: application
