name: Lint and run tests

on:
  push:
    paths:
      - '**.py'

jobs:
  lint-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create Anaconda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: tactool
        environment-file: environment.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Lint
      shell: bash -l {0}
      run: flake8

    - name: Test
      shell: bash -l {0}
      run: |
        export PYTHONPATH=.
        pytest -vv test/


